version: '3'

services:
  app:
    container_name: spring_app
    command: ./gradlew bootRun
    build: ./app
    ports:
      - 80:8080
    volumes:
      - ./app:/usr/src/app/
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    container_name: mysql_db
    build: ./database
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super-secret-squirrel
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

volumes:
  mysql_data: